server:
  port: 8080
spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/news
    username: postgres
    password: sa
    poolSize: 10
  cache:
    capacity: 10
    algorithm: Redis
  redis:
    host: localhost
    port: 6379
  liquibase:
    change-log: classpath:db/db.changelog-master.yml
    enabled: true
  hibernate:
    ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
exception:
  handler:
    enabled: true
jwt:
  secret: c92cef2481ba7a58dc63485105e6c0bc289670ba31108ff8cdf6402ae92dc84e
  expiration-time: 3600000