 INSERT INTO news (time, title, text)
 VALUES
            (current_timestamp, 'News 1', 'This is news 1'),
            (current_timestamp, 'News 2', 'This is news 2'),
            (current_timestamp, 'News 3', 'This is news 3'),
            (current_timestamp, 'News 4', 'This is news 4'),
            (current_timestamp, 'News 5', 'This is news 5'),
            (current_timestamp, 'News 6', 'This is news 6'),
            (current_timestamp, 'News 7', 'This is news 7'),
            (current_timestamp, 'News 8', 'This is news 8'),
            (current_timestamp, 'News 9', 'This is news 9'),
            (current_timestamp, 'News 10', 'This is news 10'),
            (current_timestamp, 'News 11', 'This is news 11'),
            (current_timestamp, 'News 12', 'This is news 12'),
            (current_timestamp, 'News 13', 'This is news 13'),
            (current_timestamp, 'News 14', 'This is news 14'),
            (current_timestamp, 'News 15', 'This is news 15'),
            (current_timestamp, 'News 16', 'This is news 16'),
            (current_timestamp, 'News 17', 'This is news 17'),
            (current_timestamp, 'News 18', 'This is news 18'),
            (current_timestamp, 'News 19', 'This is news 19'),
            (current_timestamp, 'News 20', 'This is news 20');